MyHardwareWeb/MyHardware/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using MyHardware.ViewModel;
using MyHardwareWeb.Application.Interfaces;

namespace MyHardware.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomerService _customerService;

        public CustomerController(
            ICustomerService customerService)
        {
            _customerService = customerService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost("save")]
        [ValidateAntiForgeryToken]
        public IActionResult Save(CustomerViewModel customerModel)
        {
            _customerService.Save(customerModel);
            TempData["success"] = "Cliente criado com sucesso.";
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            var currentCustomer = _customerService.FindByIdAsync(id);
            if (currentCustomer is null)
                return NotFound();
            return View(currentCustomer);
        }

        [HttpPost("edit")]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CustomerViewModel customerModel)
        {
            _customerService.Edit(customerModel);
            TempData["success"] = "Cliente alterado com sucesso.";
            return RedirectToAction("Index");
        }

        #region -------- Private Methods ----------
        private void Validate(CustomerViewModel model)
        {
            if (String.IsNullOrEmpty(model.Name))
            {
                ModelState.AddModelError("Name", "Preencha o nome.");
            }
            return;
        }
        #endregion

        #region --------------Export--------------
        //[HttpGet("export")]
        //[ValidateAntiForgeryToken]
        //public IActionResult Export()
        //{
        //    _customerService.ExportAllCustomer();
        //    return Ok();
        //}
        #endregion
    }
}

MyHardwareWeb/MyHardware/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using static MyHardware.Utility.Constants;
using MyHardware.ViewModel;
using MyHardwareWeb.Application.Interfaces;
using MyHardware.Utils;

namespace MyHardware.Controllers
{
    public class LoginController : Controller
    {
        private readonly IUserService _userService;
        private readonly ILogger<LoginController> _logger;

        public LoginController(IUserService userService,
            ILogger<LoginController> logger)
        {
            _userService = userService;
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }
        public async Task<IActionResult> ValidatePassword(UserViewModel model)
        {
            await Validate(model);
            if (!ModelState.IsValid)
            {
                var errors = ModelState.GetModelErrors();
                return BadRequest(new { errors });
            }

            TempData["success"] = "Login Efetuado com sucesso.";
            return Ok();
        }

        [HttpPost("save")]
        [ValidateAntiForgeryToken]
        public IActionResult Save(UserViewModel userModel)
        {

            _userService.Save(userModel);
            TempData["success"] = "Usuário criado com sucesso.";
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            if (id == DefaultValue.Inactive)
            {
                return NotFound();
            }
            var currentUser = _userService.FindById(id);
            if (currentUser == null)
            {
                return NotFound();
            }
            return View(currentUser);
        }

        [HttpPost("edit")]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(UserViewModel userModel)
        {
            _userService.Edit(userModel);
            TempData["success"] = "Usuário alterado com sucesso.";
            return RedirectToAction("Index");
        }

        public IActionResult GetRegisterDialog()
        {
            return PartialView("_RegisterUserPartial"); 
        }

        #region ----------Private Methods-----------
        private async Task Validate(UserViewModel model)
        {
            if (String.IsNullOrEmpty(model.Email))
            {
                ModelState.AddModelError("Email", "Preencha o e-mail.");
            }

            if (ModelState.ErrorCount == 0 && String.IsNullOrEmpty(model.Password))
            {
                ModelState.AddModelError("Password", "Preencha a Senha.");
            }

            if (ModelState.ErrorCount == 0)
            {
                var isValid = await _userService.ValidatePassword(model.Email, model.Password);
                if (!isValid)
                    ModelState.AddModelError("Password", "Email ou senha incorretos.");
            }

            return;
        }
        #endregion

        #region ------------Export------------
        //[HttpGet("export")]
        //[ValidateAntiForgeryToken]
        //public IActionResult Export()
        //{
        //    _userRepository.ExportAllUsers();
        //    return Ok();
        //}
        #endregion
    }
}

MyHardwareWeb/MyHardware/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using static MyHardware.Utility.Constants;
using MyHardware.ViewModel;
using AutoMapper;
using MyHardwareWeb.Application.Interfaces;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MyHardware.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        public IActionResult Index()
        {
            return View("Index");
        }

        public IActionResult Create()
        {
            ViewBag.ProductType = new SelectList(ProductType.GetComboboxList(), "Value", "Text");
            return View("Form");
        }

        [HttpPost("save")]
        [ValidateAntiForgeryToken]
        public IActionResult Save(ProductViewModel productModel)
        {
            _productService.Save(productModel);
            TempData["success"] = "Produto criado com sucesso.";
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            if (id == DefaultValue.Inactive)
            {
                return NotFound();
            }
            var currentProduct = _productService.FindById(id);
            if (currentProduct is null)
            {
                return NotFound();
            }
            return View(currentProduct);
        }

        [HttpPost("edit")]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ProductViewModel productModel)
        {
            _productService.Edit(productModel);
            TempData["success"] = "Produto alterado com sucesso.";
            return RedirectToAction("Index");
        }

        #region -------- Private Methods ----------
        private void Validate(ProductViewModel model)
        {
            if (String.IsNullOrEmpty(model.Name))
            {
                ModelState.AddModelError("Name", "Preencha o nome.");
            }
            return;
        }
        #endregion

        #region -----------------Export---------------------
        //[HttpGet("export")]
        //[ValidateAntiForgeryToken]
        //public IActionResult Export()
        //{
        //    _productRepository.ExportAllProducts();
        //    return Ok();
        //}
        #endregion
    }
}

MyHardwareWeb/MyHardware/Controllers/SupplierController.cs
using Microsoft.AspNetCore.Mvc;
using static MyHardware.Utility.Constants;
using MyHardware.ViewModel;
using MyHardwareWeb.Application.Interfaces;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MyHardware.Controllers
{
    public class SupplierController : Controller
    {
        private readonly ISupplierService _supplierService;

        public SupplierController(ISupplierService supplierService)
        {
            _supplierService = supplierService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            ViewBag.ProductType = new SelectList(ProductType.GetComboboxList(), "Value", "Text");
            return View("Form");
        }

        [HttpPost("save")]
        [ValidateAntiForgeryToken]
        public IActionResult Save(SupplierViewModel supplierModel)
        {
            _supplierService.Save(supplierModel);
            TempData["success"] = "Fornecedor criado com sucesso.";
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            if (id == DefaultValue.Inactive)
            {
                return NotFound();
            }
            var currentSupplier = _supplierService.FindById(id);
            if (currentSupplier == null)
            {
                return NotFound();
            }
            return View(currentSupplier);
        }

        [HttpPost("edit")]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(SupplierViewModel supplierModel)
        {
            _supplierService.Edit(supplierModel);
            TempData["success"] = "Fornecedor alterado com sucesso.";
            return RedirectToAction("Index");
        }

        public IActionResult GetInviteDialog()
        {
            return PartialView("_InviteCustomerPartial");
        }

        #region -------- Private Methods ----------
        private void Validate(SupplierViewModel model)
        {
            if (String.IsNullOrEmpty(model.Name))
            {
                ModelState.AddModelError("Name", "Preencha o nome.");
            }
            return;
        }
        #endregion

        #region ----------------Export--------------------
        //[HttpGet("export")]
        //[ValidateAntiForgeryToken]
        //public IActionResult Export()
        //{
        //    _supplierRepository.ExportAllSupplier();
        //    return Ok();
        //}
        #endregion
    }
}

MyHardwareWeb/MyHardware/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>@ViewData["Title"] - MyHardware</title>
  <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
  <link rel="stylesheet" href="~//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
  <link rel="stylesheet" href="~/MyHardware.styles.css" asp-append-version="true" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
</head>
<body>
  <header class="header-main">
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
      <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Login" asp-action="Index">MyHardware</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
          <ul class="navbar-nav flex-grow-1">
            <li class="nav-item">
              <a class="nav-link text-dark" asp-area="" asp-controller="Supplier" asp-action="Index">Fornecedor</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Produto</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Cliente</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <header class="header-login">
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">MyHardware</a>
      </div>
    </nav>
  </header>
  <div class="container">
    <main role="main" class="pb-3" style="height: 80vh">
      @RenderBody()
    </main>
  </div>
  <footer class="border-top footer text-muted">
    <div class="container">
      &copy; 2022 - MyHardware - <a asp-area="" asp-controller="Login" asp-action="Index">Privacy</a>
    </div>
  </footer>
  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
  <script src="~/js/App.js"></script>
  <script src="~/js/Login.js"></script>
  <script src="~/js/Product.js"></script>
  <script src="~/js/Supplier.js"></script>
  @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MyHardwareWeb/MyHardware/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
  <script type="text/javascript">
    toastr.success('@TempData["success"]');
  </script>
}
@if (TempData["error"] != null)
{
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
  <script type="text/javascript">
    toastr.error('@TempData["error"]');
  </script>
}